// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubojqbweeakkxmumxnko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVib2pxYndlZWFra3htdW14bmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzIwMjUsImV4cCI6MjA3MTkwODAyNX0.sHwcBHXTvx-2xEdC4VSkLJWEo6Pf4SdR6agRhcT2rW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});